baseURL = 'https://B0o07.github.io/'
languageCode = 'en-us'
title = 'Nickye | Zero to Hero in CyberSec'
theme = 'PaperMod'

[params]
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowCodeCopyButtons = true